# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://travis-ci.org/
language: node_js
node_js:
  - "8"
install:
  - yarn add
script:
  - yarn run build
branches:
  only:
    - master
